diskSpace: 10Gi
modrinthProjects:
  - explorers-compass
  - journeymap
  - natures-compass
  - pixelmon
spigotPluginIds:
  - 6245 # InteractiveChat
  - 28140 # LuckPerms
  - 34315 # Vault
  - 81534 # Chunky
  - 83767 # HuskHomes
  - 84278 # ChunkyBorder
  - 108700 # Plugin Portal
worldUrl: ""
