minecraftVersion: "1.21.11"
modrinthProjects:
  - chunky
  - chunkyborder
  - essentialsx
  - fastasyncworldedit
  - huskhomes
  - interactivechat
  - luckperms
  - pluginportal
  - placeholderapi
  - vane
worldUrl: ""
